In [1]:
import pandas as pd

In [225]:
# loading the spreadsheet
lol = pd.read_csv('lol.csv')
df = pd.DataFrame(lol)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12844 entries, 0 to 12843
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Index       12844 non-null  int64
 1   institute   12835 non-null  object
 2   branch      12835 non-null  object
 3   Unnamed: 3  0 non-null      float64
 4   seat_type   12835 non-null  object
 5   gender      12355 non-null  object
 6   or          12150 non-null  float64
 7   cr          12039 non-null  float64
 8   year        12844 non-null  int64
dtypes: float64(3), int64(2), object(4)
memory usage: 903.2+ KB

In [246]:
# # Cleaning data:

# # Deleting useless columns like index and unnamed:3
# df = df.drop(df.columns[[0,3]], axis=1)

# # Dropping NA values from institute
# df = df.dropna(thresh = 3)

# df.fillna(0)
# # Converting float values to int
# df['or'] = pd.to_numeric(df['or'], errors='coerce').astype('Int64')
# df['cr'] = pd.to_numeric(df['cr'], errors='coerce').astype('Int64')

# # Selecting Seat_type which are open
# df = df[df['seat_type'] == 'OPEN']

# # Selecting gender which is neutral
# df = df[df['gender'] != 'Female-only (including Supernumerary)']
# df['gender'] = "Neutral"

# #Easiest course to get ie with max cr for every year
max_each_year = df.groupby('year')['cr'].transform('max')
easy_comb = df[df['cr']==max_each_year]
easy_comb.sort_values(by = 'cr', ascending = False)

#Easiest course to get ie with max cr for each institute for a given year
selected_year = int(input("Select a Year from 2016 to 2025:"))
df_selected_year = df[df['year'] == selected_year]
max_selected_year = df_selected_year[df_selected_year['cr']== df_selected_year.groupby('institute')['cr'].transform('max')]
max_selected_year.sort_values(by = 'cr', ascending = False)

Select a Year from 2016 to 2025: 2025

,institute,branch,seat_type,gender,or,cr,year
12708,Indian Institute of Technology (BHU) Varanasi,"Architecture (5 Years, Bachelor of Architecture)",OPEN,Neutral,18471,20792,2025
12384,Indian Institute of Technology Kharagpur,"Architecture (5 Years, Bachelor of Architecture)",OPEN,Neutral,9970,19141,2025
12838,Indian Institute of Technology Dharwad,"Interdisciplinary Sciences (5 Years, Bachelor ...",OPEN,Neutral,16198,18979,2025
12684,Indian Institute of Technology (ISM) Dhanbad,"Physical Science (5 Years, Integrated Bachelor...",OPEN,Neutral,15891,18368,2025
12460,Indian Institute of Technology Jodhpur,"Chemistry with Specialization (4 Years, Bachel...",OPEN,Neutral,14939,18310,2025
12820,Indian Institute of Technology Jammu,"Materials Engineering (4 Years, Bachelor of Te...",OPEN,Neutral,16833,18156,2025
12612,Indian Institute of Technology Roorkee,"Architecture (5 Years, Bachelor of Architecture)",OPEN,Neutral,12842,17665,2025
12302,Indian Institute of Technology Mandi,"BS in Chemical Sciences (4 Years, Bachelor of ...",OPEN,Neutral,13425,17491,2025
12774,Indian Institute of Technology Bhilai,Materials Science and Metallurgical Engineerin...,OPEN,Neutral,14920,17478,2025
12556,Indian Institute of Technology Patna,B. Tech in CE. - M. Tech. in Geotechnical Eng...,OPEN,Neutral,16406,16815,2025
12788,Indian Institute of Technology Palakkad,"Civil Engineering (4 Years, Bachelor of Techno...",OPEN,Neutral,14109,16753,2025
12800,Indian Institute of Technology Tirupati,"Civil Engineering (4 Years, Bachelor of Techno...",OPEN,Neutral,8956,16548,2025
12258,Indian Institute of Technology Bhubaneswar,Metallurgical and Materials Engineering (4 Yea...,OPEN,Neutral,11591,16268,2025
12694,Indian Institute of Technology Ropar,"Digital Agriculture (4 Years, Bachelor of Tech...",OPEN,Neutral,11311,14480,2025
12786,Indian Institute of Technology Goa,"Mechanical Engineering (4 Years, Bachelor of T...",OPEN,Neutral,9914,13451,2025
12336,Indian Institute of Technology Delhi,"Design (4 Years, Bachelor of Technology)",OPEN,Neutral,7813,12217,2025
12374,Indian Institute of Technology Indore,Metallurgical Engineering and Materials Scienc...,OPEN,Neutral,8439,11274,2025
12550,Indian Institute of Technology Gandhinagar,"Materials Engineering (4 Years, Bachelor of Te...",OPEN,Neutral,7239,11066,2025
12742,Indian Institute of Technology Guwahati,"Biosciences and Bioengineering (4 Years, Bache...",OPEN,Neutral,6303,10727,2025
12482,Indian Institute of Technology Kanpur,"Chemistry (4 Years, Bachelor of Science)",OPEN,Neutral,8553,10482,2025
12512,Indian Institute of Technology Madras,"Biological Science (4 Years, Bachelor of Science)",OPEN,Neutral,3268,10290,2025
12446,Indian Institute of Technology Hyderabad,"Industrial Chemistry (4 Years, Bachelor of Tec...",OPEN,Neutral,7757,10043,2025
12262,Indian Institute of Technology Bombay,"Applied Geophysics (4 Years, Bachelor of Science)",OPEN,Neutral,6087,8343,2025